@startuml

autonumber

actor Actor as JDrawingFrame
participant "shapeC: ShapeController" as shapeController
participant "shapeFac: ShapeFactory" as shapeFac
participant "s1: Square" as Square
participant "c1: Circle" as Circle
participant "cs: CompoundShape" as CompoundShape
participant "historyC: HistoryController" as histController

activate JDrawingFrame
JDrawingFrame -> shapeController ** : ShapeController()
JDrawingFrame -> shapeFac ** : ShapeFactory()
JDrawingFrame -> histController ** : HistoryController()

JDrawingFrame -> JDrawingFrame : mouseClicked(MouseEvent evt)
JDrawingFrame -> JDrawingFrame : createShape(Shapes Square, int 90, int 90)
JDrawingFrame -> shapeController ++ : createSimpleShape(Shapes Square, int 90, int 90)
shapeController -> shapeFac ++-- : createSimpleShape(Shapes Square, int 90, int 90)
shapeFac -> Square ** : Square(int 90, int 90)
deactivate shapeFac

JDrawingFrame -> histController ++ : add(new CreateCommand(SimpleShape null, SimpleShape square))
deactivate histController

JDrawingFrame -> JDrawingFrame : mouseClicked(MouseEvent evt)
JDrawingFrame -> JDrawingFrame : createShape(Shapes Circle, int 120, int 250)
JDrawingFrame -> shapeController ++ : createSimpleShape(Shapes Circle, int 120, int 250)
shapeController -> shapeFac ++-- : createSimpleShape(Shapes Circle, int 120, int 250)
shapeFac -> Circle ** : Circle(int 120, int 250)
deactivate shapeFac

JDrawingFrame -> histController ++ : add(new CreateCommand(SimpleShape null, SimpleShape circle))
deactivate histController

JDrawingFrame -> JDrawingFrame : mouseClicked(MouseEvent evt)
JDrawingFrame -> JDrawingFrame : shapeIsSelect(int 110, int 90)
JDrawingFrame -> shapeController ++ : shapeIsSelect(List<SimpleShape> shapesList, int 110, int 250)
shapeController -> Circle : clickedOnShape(int 110, int 90) : false
shapeController -> Square -- : clickedOnShape(int 110, int 90) : true

JDrawingFrame -[#0000FF]> JDrawingFrame : System.out.println("Forme selectionnée")

JDrawingFrame -> JDrawingFrame : mouseClicked(MouseEvent evt)
JDrawingFrame -> JDrawingFrame : shapeIsSelect(int 110, int 90)
JDrawingFrame -> Circle : clickedOnShape(int 110, int 260) : true
JDrawingFrame -[#0000FF]> JDrawingFrame : System.out.println("Forme selectionnée")

JDrawingFrame -> CompoundShape ** : CompoundShape([SimpleShape s1, SimpleShape c1])

JDrawingFrame -> JDrawingFrame : mouseDragged(MouseEvent evt)
JDrawingFrame -> CompoundShape ++ : moveTo(int 400, int 300)
CompoundShape -> Square ++ : moveTo(int 400, int 300)
CompoundShape -> Circle ++-- : moveTo(int 430, int 460)
deactivate Square
deactivate Circle

JDrawingFrame -> JDrawingFrame : reDrawAll()
JDrawingFrame -> Square ++ : draw(Graphics2D g2, float, 2,0)
JDrawingFrame -> Circle ++ : draw(Graphics2D g2, float, 2,0)

' Objectif de ce diagram :
' On a déjà notre frame diponible
' On va ajouter une forme Circle + Triangle que l'on va grouper puis déplacer

deactivate JDrawingFrame
@enduml