@startuml

autonumber

actor Actor as JDrawingFrame
participant "shapeC: ShapeController" as shapeController
participant "shapeFac: ShapeFactory" as shapeFac
participant "c1: Circle" as Circle
participant "historyC: HistoryController" as histController


activate JDrawingFrame
JDrawingFrame -> shapeController ** : ShapeController()
JDrawingFrame -> shapeFac ** : ShapeFactory()
JDrawingFrame -> histController ** : HistoryController()

JDrawingFrame -> JDrawingFrame : mouseClicked(MouseEvent evt)
JDrawingFrame -> JDrawingFrame : createShape(Shapes Circle, int 120, int 250)
JDrawingFrame -> shapeController ++ : createSimpleShape(Shapes Circle, int 120, int 250)
shapeController -> shapeFac ++-- : createSimpleShape(Shapes Circle, int 120, int 250)
shapeFac -> Circle ** : Circle(int 120, int 250)
deactivate shapeFac

JDrawingFrame -> histController ++ : add(new CreateCommand(SimpleShape null, SimpleShape circle))
deactivate histController

JDrawingFrame -> JDrawingFrame : mouseClicked(MouseEvent evt)
JDrawingFrame -> JDrawingFrame : shapeIsSelect(int 110, int 250)
JDrawingFrame -> shapeController ++ : shapeIsSelect(List<SimpleShape> shapesList, int 110, int 250)
shapeController -> Circle ++-- : clickedOnShape(int 110, int 250)
Circle -> Circle : getX()
Circle -> Circle -- : getY()

JDrawingFrame -> JDrawingFrame : mouseDragged(MouseEvent evt)
JDrawingFrame -> Circle ++ : moveTo(int 200, int 250)
JDrawingFrame -> Circle -- : draw(Graphics2D g2, float, 2,0)
JDrawingFrame -> JDrawingFrame : reDrawAll()

JDrawingFrame -> JDrawingFrame : mouseReleased(MouseEvent evt)
JDrawingFrame -> histController ++ : add(new MoveCommand(SimpleShape oldCircle, SimpleShape newCircle))
deactivate histController

JDrawingFrame -> histController ++ : undo(List<SimpleShape> shapesList)
histController -> MoveCommand : execute(List<SimpleShape> shapesList)
histController -> histController : pop(Command lastCommand)
JDrawingFrame -> JDrawingFrame : reDrawAll()
deactivate histController


' Objectif de ce diagram :
' On a déjà notre frame diponible
' On va ajouter une forme Circle + Triangle que l'on va grouper puis déplacer

deactivate JDrawingFrame
@enduml